package com.tienlx.myplaylist.entity;
// Generated 12/02/2015 11:33:24 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Song generated by hbm2java
 */
@Entity
@Table(name = "song"
        , catalog = "yourplaylist"
)
public class Song implements java.io.Serializable {


    private String id;
    private String title;
    private String titleSearch;
    private String artist;
    private String artistSearch;
    private long playCount;
    private String category;

    public Song() {
    }


    public Song(String id, String title, String titleSearch, String artist, String artistSearch, long playCount) {
        this.id = id;
        this.title = title;
        this.titleSearch = titleSearch;
        this.artist = artist;
        this.artistSearch = artistSearch;
        this.playCount = playCount;
    }

    public Song(String id, String title, String titleSearch, String artist, String artistSearch, long playCount, String category) {
        this.id = id;
        this.title = title;
        this.titleSearch = titleSearch;
        this.artist = artist;
        this.artistSearch = artistSearch;
        this.playCount = playCount;
        this.category = category;
    }

    @Id
    @Column(name = "Id", unique = true, nullable = false, length = 10)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "Title", nullable = false, length = 50)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "TitleSearch", nullable = false, length = 50)
    public String getTitleSearch() {
        return this.titleSearch;
    }

    public void setTitleSearch(String titleSearch) {
        this.titleSearch = titleSearch;
    }

    @Column(name = "Artist", nullable = false, length = 50)
    public String getArtist() {
        return this.artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    @Column(name = "ArtistSearch", nullable = false, length = 50)
    public String getArtistSearch() {
        return this.artistSearch;
    }

    public void setArtistSearch(String artistSearch) {
        this.artistSearch = artistSearch;
    }

    @Column(name = "PlayCount", nullable = false)
    public long getPlayCount() {
        return this.playCount;
    }

    public void setPlayCount(long playCount) {
        this.playCount = playCount;
    }

    @Column(name = "Category", length = 50)
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }


}


