//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.08 at 12:58:59 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://yourplaylist.tk/Schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tienlx.myplaylist.jaxb.playlist;
